### ISSUE TITLE
Merge INRA/Elixir Wheat Ontology With T3/CIMMYT

### ISSUE THREAD

**Issue by cpommier** [Planteome/CO_321-wheat-traits#2]

**Comment by marieALaporte** [comment]
@cpommier looking quickly at the file, I realize that you didn't start from the T3 branch. I thought that we agreed that you start from that branch?
If you cannot, I will need to think on how to merge it at best...
Some quick comments, could you please provide a description for all the traits and create some method names? N.A. is confusing. Thanks

**Comment by cpommier** [comment]
@marieALaporte my mistake, I'll correct that from the right branch
For N.A. I propose to put explicitly Not Available

**Comment by marieALaporte** [comment]
Could you do something like "Trait X method" instead, so they don't all end up with the same name? I can do it once you push it to the right branch if you prefer. 
But I cannot not add the description though. 
Tom, our new curator, will send you comments once the new file is there.
Thanks

**Comment by cpommier** [comment]
Done the rebranching. I have added you as a reviewer as I don't know Tom's github ID.
Regarding the trait Method, we have created a single method N.A. shared with the same ID used for all unknown Method. Semantically it makes more sense, it simply means that the traceability of the Method has been lost. Doing a generic Trait x method is strange to me, it somehow hide the fact that we have no clue of the method. 
Except if there is a technical problem with some tools, I would really advocate for using something that is closer to reality.

**Comment by cpommier** [comment]
@marieALaporte could you assign this to Tom please ?

**Comment by cpommier** [comment]
Decisions after the call Tom, @marieALaporte Célia.

- MethodeName = na replaced by MethodeName = undefined
- Generate unique ID for all undefined method
- Explore the possibility to have MethodeName = "undefined method for trait XXX" later

**Comment by cpommier** [comment]
Scale: favor using ad hoc crop ontology ids rather than unit ontologies ones.
For all ontologies

**Comment by TomHazekam** [comment]
Ping

**Comment by cpommier** [comment]
@marieALaporte @TomHazekam
We did the planed correction, is that fine with you ?
