### ISSUE TITLE
Duplicate variable: CO_321:0501001	and CO_321:0501002 Ant_E_jd 

### ISSUE THREAD

**Issue by cpommier** [Planteome/CO_321-wheat-traits#9]
Those two variables are axactly the same. Can we remove  CO_321:0501002 or is it used in T3 ?
If we can remove it, let us know we will take care of it.

**Comment by cooperl09** [comment]
These are the duplicated variables: 
[Term]
id: CO_321:0501001
name: wheat ant_e_jd variable
synonym: "ANT_jd" EXACT []
relationship: variable_of CO_321:0000121 ! anthesis time
relationship: variable_of CO_321:0000832 ! ant ds65 date estimation
relationship: variable_of CO_321:0000855 ! Julian date (JD)
is_a: CO_321:0000121 ! anthesis time

[Term]
id: CO_321:0501002
name: wheat ant_e_jd variable
synonym: "ANT_jd" EXACT []
relationship: variable_of CO_321:0000121 ! anthesis time
relationship: variable_of CO_321:0000832 ! ant ds65 date estimation
relationship: variable_of CO_321:0000855 ! Julian date (JD)
is_a: CO_321:0000121 ! anthesis time

It does not look like T3 is using CO_321:0501002
https://wheat.triticeaetoolbox.org/tools/onto/

**Comment by marieALaporte** [comment]
Thanks @cpommier @cooperl09. I fixed the issue, so closing now.
